### ISSUE TITLE
Example Improvement – ts interop example to employ new template and include data sending from ts (not quite a bug report)

### ISSUE THREAD

**Issue by kumkee** [elm-land/elm-land#130]
## Problem

> What problem did you run into when using Elm Land?

This is not a problem rather two improvement suggestions to the current typescript interop example -
1. Employing the new [`interop.ts` template in 0.19.2](https://github.com/elm-land/elm-land/blob/c7dbae6b4adc6c0f8a420a5246f3ea10d005ab22/projects/cli/src/templates/_elm-land/customizable/interop.ts)
2. Adding data reception in elm from typescript.

~I'll open a PR to implement both.~ 
[Here is the link to the PR implementing the two suggestions](https://github.com/elm-land/elm-land/pull/131). 

## Your setup

> - What operating system (Mac/Windows/Linux) are you using? 

`Debian GNU/Linux 12 (bookworm)`/kernel `5.15.90.1-microsoft-standard-WSL2`

> - Please share the output of the following commands:

- `node -v`: `v20.4.0`
- `elm-land -v`: `v0.19.2`

**Comment by ryannhg** [comment]
I'm going to close this issue for now, I'm not sure what the recommendation for using TypeScript should be, and would rather not express an opinion in the official repo just now.

Regardless, I'm grateful that you're taking initiative to improve Elm Land! ❤️

**Comment by kumkee** [comment]
> I'm going to close this issue for now, I'm not sure what the recommendation for using TypeScript should be, and would rather not express an opinion in the official repo just now.
> 
> Regardless, I'm grateful that you're taking initiative to improve Elm Land! ❤️

The template part is opinionated. How about the data-receiving part? 
There is no example of sending data from ts/js to elm.
