### ISSUE TITLE
Add tailwind example

### ISSUE THREAD

**Issue by domenkozar** [elm-land/elm-land#133]
Even just a link to https://github.com/dz0ny/elm-land-tailwind on the main page will help a lot of people that ask this question.

**Comment by jakepears** [comment]
i'd like to contribute. please describe the suggestion a bit more

**Comment by mawilms** [comment]
Maybe a minimal tailwind implementation could be behind a feature flag like:

elm-land init my_project --tailwindcss

This way we make sure, that all users use the same tailwind setup which could simplify support request.

**Comment by ryannhg** [comment]
> i'd like to contribute. please describe the suggestion a bit more

I would love to have an `examples/20-tailwindcss` in the official repos example folder 📁

If you're interested in contributing, all you'd need to do would be include that code.

---

First, I want to confirm with @dz0ny if it's okay to move their example into the official Elm Land repo.

Maybe we should include a link back to the original repo for credit, too?

**Comment by dz0ny** [comment]
Sure, go ahead.
