### ISSUE TITLE
Feature Request: Hot-reload persist app state

### ISSUE THREAD

**Issue by silky** [elm-land/elm-land#152]
Loving elm-land!

It would be great if the hot-reload would persist the present state of the model. I think I've seen a few other frameworks do this; it would be extremely convenient and useful!

Thanks :)

**Comment by ryannhg** [comment]
( This feature is coming in the next big release, and will be powered by Simon Lydell's elm-watch HMR work! )

**Comment by kantuni** [comment]
@ryannhg can we also replace `tsc` with `esbuild`? The compile times are killing me!

**Comment by ryannhg** [comment]
> @ryannhg can we also replace `tsc` with `esbuild`? The compile times are killing me!

I'm definitely open to this!

**Comment by ryan-haskell** [comment]
Good news– I just released [📦 Elm Land v0.20.0](https://github.com/elm-land/elm-land/releases/tag/v0.20.0) which resolves this issue (more details in the release linked above)

Thanks for improving Elm Land! 🌈 

---

Also, @kantuni - I've removed the slow TypeScript build step, it's now doing the normal Vite things!

**Comment by kantuni** [comment]
Thanks a ton, @ryan-haskell!
