### ISSUE TITLE
🐞 Bug – qualifying imports gives weird unexpected type annotation error

### ISSUE THREAD

**Issue by kutyel** [elm-land/elm-land#157]
## Problem

I tried just using type aliases in my Shared.elm module and it broke elm-land 😮 

<img width="893" alt="Screenshot 2023-12-26 at 17 36 58" src="https://github.com/elm-land/elm-land/assets/5127501/3a803ec3-baa3-4fa8-a3e3-cffb75e301d5">

## Your setup

Very easy to reproduce, you just need to put this instead in your `src/Shared.elm` file

```elm
import Json.Decode as Decode
```

**Comment by ryannhg** [comment]
Hey Flavio!

This is a known limitation at the moment...

I need to take a look at how we parse ASTs in general for a later release, the current approach seems to lead to performance issues when detecting page/shared/layout user code. 

It's not ideal– but the workaround isn't _too_ bad in the meantime: Avoiding aliases for the small handful of "Elm Land specific" functions

Going to close this issue for now, but hopefully I'll be able to make the AST detection more flexible in the future... 🤞
