### ISSUE TITLE
Support proxying 

### ISSUE THREAD

**Issue by domenkozar** [elm-land/elm-land#159]
I understand that the current stance is not to expose Vite server options.

We could support our own format for proxying in `elm-land.json`.

Based on https://vitejs.dev/config/server-options.html#server-proxy

```
{
  "proxy" {
    "/api": {
      "target": "http://127.0.0.1:8080",
    }
  }
}
```

**Comment by ryannhg** [comment]
Hey @domenkozar – this issue was resolved with v0.19.5 (#160)

Thanks for improving Elm Land! 🌈
