### ISSUE TITLE
Request - Have a clearer story around ports and pages

### ISSUE THREAD

**Issue by silky** [elm-land/elm-land#165]
The recommended way to use ports means that all ports are available **on all pages**, even though that's not what one might naively imagine or want.

It would be nice if there was a way to get the current page, at least, in JavaScript, so you can select the appropriate functionality you are interested in.

**Comment by silky** [comment]
As an example, it would be extremely useful to hook into the page-change event; but it seems at present there is no way to do that.

**Comment by vladimirlogachev** [comment]
It is nice that all effects of `Shared.init` are run only once per application load.

**Comment by silky** [comment]
I don't disagree; completely.

But it is a _little_ confusing that they aren't evaluated.

For example, one result is that if you have a JS widget you _only_ want to appear on one page, you need are forced to _hide_ it on every page it _isn't_ present on, because once it's injected into the dom (say at the body element) it stays there.

I think this is a bit confusing ... (but maybe I just made a mistake?)

**Comment by vladimirlogachev** [comment]
Just an idea: I would try to play with the layout code.
Another idea: I would try to batch some effect together with the path change effect

**Comment by silky** [comment]
Neither of those really work here.

The point is, because the dom change happens outside elm, and it persists between pages, the _only_ option is to leak details of one page to the other (i.e. the non-widget-wanting pages must actively request that it is hidden).

My feeling is that this is wrong; if the "pages" are really "Pages" then this just shouldn't be going wrong; but it does, but not for a reason I can clearly identify at the moment.

**Comment by vladimirlogachev** [comment]
If you define some function and run it on every page's own `init`, will it solve your problem (at least technically)?

**Comment by silky** [comment]
That's exactly what I do, let's say I have:

- WidgetPage: `init = { ... Effect.batch [ showWidget ] }`
- NormalPage: `init = { ... Effect.batch [ hideWidget ] }`

what's annoying is that i must hide everywhere

one alternative, as i proposed above, is that i hide _in the shared init_; only once. but i agree that this isn't ideal.

i don't know a good alternative; but it at least seems related to the issue that ports are a bit "quirky" to say the least, in that they are always present no matter the page, etc, etc, etc.

**Comment by ryan-haskell** [comment]
Hey @silky, the GitHub issues for this repo are only intended for bug reports.

We have a community [PR Template](https://github.com/elm-land/elm-land/blob/main/.github/ISSUE_TEMPLATE/---bug-report.md) to help guide discussions like these to our Discord at https://join.elm.land

I'm going to close this issue, but please feel free to continue the discussion in `#general` or `#docs` if you think there are ways to improve the story around ports
