### ISSUE TITLE
🐞 Bug – Auth has no notion of errors

### ISSUE THREAD

**Issue by domenkozar** [elm-land/elm-land#167]
I was hoping that

```elm
Auth.Action.showLoadingPage { title = "Error", body = [ Html.text "An error occurred." ] }
```

would do what I'd like.

I'd suggest to introduce `Auth.Action.showPage` and remove `viewLoadingPage`, this way the user can show error or loading pages when needed.

**Comment by ryan-haskell** [comment]
Good news– I just released [📦 Elm Land v0.20.0](https://github.com/elm-land/elm-land/releases/tag/v0.20.0) which resolves this issue (more details in the release linked above)

Thanks for improving Elm Land! 🌈
