### ISSUE TITLE
Publish the elm-land extension to the open vscodium registry

### ISSUE THREAD

**Issue by ludat** [elm-land/elm-land#172]
Right now if you use [vscodium](https://vscodium.com/) (a truly open source version of vscode) you don't have access to the official microsoft handled store (because microsoft doesn't allow clients other than their official builds of vscode) so you can't install the `elm-land` extension.

The solution implemented by most extension developers is to republish their extension to the [open registry](https://open-vsx.org/) as well as the microsoft owned one

**Comment by ryan-haskell** [comment]
Hi @ludat,

I just created a "Release" for the VS Code plugin, including the latest `.vsix` file available for download:
https://github.com/elm-land/vscode/releases/tag/v0.2.4

I'll keep those GitHub releases up-to-date for any future updates, for any folks not using the Microsoft registry.

Although I am not interested in maintaining the open-vsx.org registry entry, you have __my full permission__ to republish the Elm Land VS Code plugin on that registry under your account.
