### ISSUE TITLE
🐞 Bug – Page doesn't load if the path has more than two components `/one/two`

### ISSUE THREAD

**Issue by ludat** [elm-land/elm-land#174]
## Problem

After upgrading to 0.20.0, the app just shows a blank page for pages that have nested routes, after looking at the console I see that the html points to `<script type="module" src="./.elm-land/server/main.js"></script>` so the resolved route gets a 404 from the server

## Your setup

>    - `node -v`: `v20.11.1`
>    - `elm-land -v`: `🌈  Elm Land (v0.20.0) is currently installed.`

**Comment by ryan-haskell** [comment]
Thank you, @ludat – this issue has been fixed in a PR that will go out later tonight! 🚀

**Comment by ludat** [comment]
Just checked and this is fixed by #175, thanks!
