### ISSUE TITLE
🐞 Bug – Wrong path detected for `elm`

### ISSUE THREAD

**Issue by heyakyra** [elm-land/elm-land#36]
For some reason, `elm` is sought from the wrong path `/var/home/kyra/.local/lib/node_modules/.bin/elm` instead of `/var/home/kyra/.local/lib/node_modules/elm/bin/elm` (the difference being `.bin` instead of `elm/bin`)

```
elm-land build
/var/home/kyra/.local/lib/node_modules/elm-land/node_modules/node-elm-compiler/dist/index.js:85
            .on('error', function (err) { throw (err); });
                                          ^

Error: spawn /var/home/kyra/.local/lib/node_modules/.bin/elm ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /var/home/kyra/.local/lib/node_modules/.bin/elm',
  path: '/var/home/kyra/.local/lib/node_modules/.bin/elm',
  spawnargs: [
    'make',
    '/var/home/kyra/repos/elon-musk-or-adolf-hitler/.elm-land/src/Main.elm',
    '--output',
    '/tmp/202285-8397-1rk1s7a.0zc7.js',
    '--optimize',
    '--report',
    'json'
  ]
}

Node.js v18.8.0
```
(also happens with node 16.x)

Any ideas how/why this occurs, or how to override this as a workaround?

**Comment by ryannhg** [comment]
Hey there!

Which version of Elm Land are you currently running? Earlier today, we released a new patch:
https://github.com/elm-land/elm-land/releases/tag/v0.16.2_bump

---

If you're trying out the alpha, please hop in our Discord #elm-land channel while we're building things out:
https://discord.gg/JgytZN3E

**Comment by heyakyra** [comment]
I hit this on 0.16.1 and 0.16.2 but i can hop on the disord tomorrow thanks

**Comment by ryannhg** [comment]
Cool– here's what I think a good next step should be:

For both the `elm-land build` and `elm-land server` command, I should make sure that things work for:

- Folks running `npm install -g elm-land@latest`
- Folks running `npm install -g elm elm-land@latest`
- Folks with a local project, running: `npm install --save-dev elm-land elm`

Ideally, I can capture both of these commands work in a `.bats` test file!

I was hoping that Elm Land could automatically install the right version of Elm for users, so no one had to worry about upgrading/using an incompatible version– but it looks like that was a bigger problem than I had originally expected 😅 

( Need to also confirm things are working for other popular package managers like `yarn`, `pnpm`, etc )

**Comment by ryannhg** [comment]
Hey @heyakyra ! 👋 

I just released a new version to address this problem:
- Here's the PR if you'd like to see what changed: 
    #37 
- Here's the new NPM package: 
    [v0.16.3](https://www.npmjs.com/package/elm-land/v/0.16.3)
 
Please re-open this issue if the problem wasn't fixed for you, and thank you for improving Elm Land!
