### ISSUE TITLE
🐞 Bug – Changes in Shared module are not detected and not recompiled by Vite

### ISSUE THREAD

**Issue by 0-gravity** [elm-land/elm-land#43]
## Problem
Changes in Shared module are not detected and not recompiled by Vite

## Your setup
OS: macOS Monterey, version: 12.6
Node: v16.17.0
Elm Land: v0.17.1

**Comment by ryannhg** [comment]
Hey @0-gravity – thank you for the bug report!

I've noticed this bug too, and it should definitely be fixed! 🔧 

---

( Also, if you could edit your description to use the Elm Land GitHub Issue template, that would mean a lot! )

Here it is again, to make it easy to copy the format: 👇 

## Problem

> What problem did you run into when using Elm Land?

## Your setup

> - What operating system (Mac/Window/Linux) are you using? Please provide a version!
> - Please share the output of the following commands:
>    - `node -v`
>    - `elm-land -v`

**Comment by ryannhg** [comment]
This has been fixed in #54 , and will be released with `v0.18.0` 🚀
