### ISSUE TITLE
🐞 Bug – Bad CPU type in executable error on Mac M1

### ISSUE THREAD

**Issue by mickeyvip** [elm-land/elm-land#45]
## Problem

Following "Hello World" example, started the server.

When navigating to the URL there is an error:

```
Failed to decode an Elm error Compilation failed
/Users/me/Library/pnpm/global/5/.pnpm/elm-land@0.17.1/node_modules/elm-land/node_modules/.bin/elm: line 13: /Users/me/Library/pnpm/global/5/.pnpm/elm-land@0.17.1/node_modules/elm-land/node_modules/.bin/../../../../../elm@0.19.1-5/node_modules/elm/bin/elm: Bad CPU type in executable
```

This is what the browser shows:
<img width="898" alt="image" src="https://user-images.githubusercontent.com/220427/194726726-46d1d4ba-e20e-4907-a2d1-76039720a258.png">

The full stack:
```
at Object.toColoredHtmlOutput (/Users/me/Library/pnpm/global/5/.pnpm/elm-land@0.17.2/node_modules/elm-land/src/vite-plugin/elm-error-json.js:121:20)
    at Context.load (/Users/me/Library/pnpm/global/5/.pnpm/elm-land@0.17.2/node_modules/elm-land/src/vite-plugin/index.js:187:35)
    at async Object.load (file:///Users/me/Library/pnpm/global/5/.pnpm/vite@3.0.9_terser@5.14.0/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35555:32)
    at async loadAndTransform (file:///Users/me/Library/pnpm/global/5/.pnpm/vite@3.0.9_terser@5.14.0/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:39827:2
```

## Your setup

OS: MacOS Monterey, 12.6
Chip: M1 Max

pnpm v7.13.1
node v18.4.0
elm-land v0.17.1

**Comment by ryannhg** [comment]
🌈 The problem is being discussed in an [Elm Land community discord thread](https://discord.com/channels/1026163159100313640/1027485020732018738)

Looks like this is working for some M1 users ( Thanks, Mario Rogic for confirming! 🙏  ) but not for others!

I'd like to capture the steps an M1 user would need to take, and replace this error with one that makes sense to an actual human being instead spitting out `Failed to decode an Elm error blablablabla Bad CPU good luck`

**Comment by mickeyvip** [comment]
It seems that this is happening when Rosetta is not installed.

What I did to make it work:

1. `brew install elm`
2. copy the `/opt/homebrew/bin/elm` binary to `/Users/me/Library/pnpm/global/5/.pnpm/elm-land@0.17.2/node_modules/elm-land/node_modules/.bin/../../../../../elm@0.19.1-5/node_modules/elm/bin/elm`

**Comment by mickeyvip** [comment]
I just tried the `@lydell/elm` package and it seems to work fine on M1.

**Comment by ryannhg** [comment]
That's great, and thank you for sharing that with me! 

Just ran the Elm Land test suite with the new `@lydell/elm` dependency instead, and it looks like it's all green:
https://github.com/elm-land/elm-land/actions/runs/3535945813

Will include this updated Elm package in the `v0.18.0` release! 🚀
