### ISSUE TITLE
🐞 Bug – Unable to set HTML attributes in the <body> tag 

### ISSUE THREAD

**Issue by ryannhg** [elm-land/elm-land#57]
## Problem

When using the [`app.html.attributes.body`](https://elm.land/guide/config/elm-land-json.html#app-html-attributes-body) property in the `elm-land.json`.

The HTML attributes are there on page load, but the Elm runtime is clearing them out when the app starts. 

( This was originally reported by Avinal in the [Elm Land Discord's `#report-a-bug` channel](https://join.elm.land). )

## Your setup

Operating System: `MacOS 12.5.1`
Node version: `v16.17.0`
Elm Land version: `v0.18.0`

## Notes

After taking a look, it appears to be caused by Elm's `Browser.document` function:

![image](https://user-images.githubusercontent.com/6187256/209225621-016cfcc4-1b50-4a3f-b58b-ba5eea8ebaa9.png)

The `patches` list has an item that tells Elm to clear out the attributes on the `<body>` tag on startup.

__Possible solutions:__
1. Do not clear out attributes
2. Do not provide `app.html.attributes.body` as an option

**Comment by avinal** [comment]
I am just wondering why it works when I build the app first and then serve. Shouldn't the elm runtime clear then as well?

**Comment by avinal** [comment]
I am in favor of removing the body attribute completely since this functionality can be entirely achieved using a div and doesn't mess with elm-runtime defaults.
