### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lydell** [elm-land/elm-land#66]
The LICENSE file says BSD-3-Clause:

https://github.com/elm-land/elm-land/blob/1a62ab6abcd246e5881a9fcbbfbb2cb9ca5ff4d0/LICENSE

But all package.json say ISC:

https://github.com/elm-land/elm-land/blob/1a62ab6abcd246e5881a9fcbbfbb2cb9ca5ff4d0/projects/cli/package.json#L30
https://github.com/elm-land/elm-land/blob/1a62ab6abcd246e5881a9fcbbfbb2cb9ca5ff4d0/projects/graphql/package.json#L19
https://github.com/elm-land/elm-land/blob/1a62ab6abcd246e5881a9fcbbfbb2cb9ca5ff4d0/projects/tooling/codegen/package.json#L21

**Comment by ryannhg** [comment]
The project is BSD-3-Clause, but the code is ISC.

**Comment by lydell** [comment]
Ok! That sounds confusing to me, but it’s your choice of course! Thanks for the reply.
